<?php

namespace iPhone\PhoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findByFirstname($firstname)
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT c FROM PhoneBundle:Contact c
            WHERE c.firstname = :firstname "
        );

        $query->setParameter(':firstname', $firstname);

        return $query->getOneOrNullResult();
    }
}
